name: Publish to NPM registry

on:
  push:
    branches:
      - master
      - release/*

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: Production 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: git config --global user.name "xprees"
      - run: git config --global user.email "xprees.developer@gmail.com"
      - uses: Aqovia/npm-version-increment@v1.1.0
        env: 
          CHANGE_TYPE = patch
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          access: public
